spring.application.name=IT_market

spring.datasource.url=${DB_URL:jdbc:postgresql://ep-young-art-aho37beu-pooler.c-3.us-east-1.aws.neon.tech/ITmarket?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASS:npg_JlQ1Cxia6fRA}
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:mariadb://localhost:3306/onlinemarket
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ========== JPA / Hibernate ==========
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Optional: Pretty-print SQL in console
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.port=${PORT:8080}


#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=shopandsell86@gmail.com
#spring.mail.username=shopandsell86@gmail.com
#spring.mail.password=eykn tdar qgmg pynw
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=online_market
spring.mail.password=${SENDGRID_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

